export type RegionConfig = {
  slug: string;
  name: string;
  intro: string;
  cities: string[];
  citySlugs: string[];
  nearby: string[];
};

export const REGIONS: Record<string, RegionConfig> = {
  "sao-paulo": { slug: "sao-paulo", name: "São Paulo e entorno", intro: "Morar em São Paulo não significa abrir mão da possibilidade de ter mais espaço, natureza e tranquilidade nos períodos de descanso. Ao redor da capital existem diferentes perfis de propriedades que podem atender quem procura uma chácara para fins de semana, uma casa de campo, um refúgio familiar ou até um imóvel pensado para temporada.\n\nEste hub do Casa na Floresta é voltado principalmente para quem parte da capital ou da Região Metropolitana e deseja ampliar a busca para municípios com perfil mais residencial, rural ou de lazer.\n\nEm vez de limitar a pesquisa a uma cidade específica, a proposta é apresentar imóveis e localidades que possam fazer sentido dentro desse objetivo. A disponibilidade depende sempre das propriedades realmente publicadas no portal.\n\nO visitante pode comparar imóveis, tipos de propriedade, regiões próximas e conteúdos relacionados antes de definir onde concentrar sua busca.", cities: ["São Paulo"], citySlugs: ["sao-paulo"], nearby: ["Campinas", "Sorocaba"] },
  "vale-do-ribeira": { slug: "vale-do-ribeira", name: "Vale do Ribeira", intro: "Encontre propriedades e refúgios publicados no portal para pesquisar no Vale do Ribeira.", cities: ["Registro", "Iguape", "Itariri", "Juquiá", "Miracatu"], citySlugs: ["registro", "iguape", "itariri", "juquia", "miracatu"], nearby: ["Sorocaba"] },
  sorocaba: { slug: "sorocaba", name: "Região de Sorocaba", intro: "A Região de Sorocaba reúne diferentes perfis de imóveis para quem procura mais espaço, contato com a natureza, lazer ou uma alternativa à vida urbana sem necessariamente se afastar dos principais centros do interior paulista.\n\nNo Casa na Floresta, este hub reúne os imóveis publicados em Sorocaba e municípios próximos, facilitando a comparação entre localidades e tipos de propriedade.\n\nAlém das ofertas disponíveis, esta página funciona como ponto de partida para quem ainda está definindo onde comprar, qual tipo de imóvel atende melhor ao projeto e quais aspectos devem ser observados antes da negociação.", cities: ["Sorocaba", "Votorantim", "Araçoiaba da Serra", "Iperó", "Boituva", "Porto Feliz", "Salto de Pirapora", "Piedade", "São Roque", "Mairinque", "Alumínio"], citySlugs: ["sorocaba", "votorantim", "aracoiaba-da-serra", "ipero", "boituva", "porto-feliz", "salto-de-pirapora", "piedade", "sao-roque", "mairinque", "aluminio"], nearby: ["Campinas"] },
  campinas: { slug: "campinas", name: "Região de Campinas", intro: "Pesquise propriedades publicadas na região de Campinas e use os municípios listados como ponto de partida.", cities: ["Campinas", "Valinhos", "Vinhedo", "Jaguariúna", "Atibaia"], citySlugs: ["campinas", "valinhos", "vinhedo", "jaguariuna", "atibaia"], nearby: ["Sorocaba", "Ribeirão Preto"] },
  "ribeirao-preto": { slug: "ribeirao-preto", name: "Região de Ribeirão Preto", intro: "Veja imóveis publicados para pesquisa na região de Ribeirão Preto e municípios associados.", cities: ["Ribeirão Preto", "Sertãozinho", "Cravinhos", "Brodowski"], citySlugs: ["ribeirao-preto", "sertaozinho", "cravinhos", "brodowski"], nearby: ["Barretos", "Bauru"] },
  barretos: { slug: "barretos", name: "Região de Barretos", intro: "Encontre imóveis publicados para pesquisa na região de Barretos.", cities: ["Barretos", "Bebedouro", "Colina", "Guaíra"], citySlugs: ["barretos", "bebedouro", "colina", "guaira"], nearby: ["Ribeirão Preto"] },
  bauru: { slug: "bauru", name: "Região de Bauru", intro: "Pesquise imóveis publicados na região de Bauru e nos municípios associados.", cities: ["Bauru", "Agudos", "Pederneiras", "Jaú"], citySlugs: ["bauru", "agudos", "pederneiras", "jau"], nearby: ["Ribeirão Preto"] },
};
