/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SlugRouteImport } from './routes/$slug'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as BuscaRouteImport } from './routes/busca'
import { Route as ChacarasRouteImport } from './routes/chacaras'
import { Route as ChalesRouteImport } from './routes/chales'
import { Route as PesqueirosRouteImport } from './routes/pesqueiros'
import { Route as RefugiosUrbanosRouteImport } from './routes/refugios-urbanos'
import { Route as SitiosRouteImport } from './routes/sitios'
import { Route as TemporadaRouteImport } from './routes/temporada'
import { Route as TiposDeImoveisRuraisRouteImport } from './routes/tipos-de-imoveis-rurais'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as ImovelSlugRouteImport } from './routes/imovel.$slug'
import { Route as TipoDePropriedadeSlugRouteImport } from './routes/tipo-de-propriedade.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugRoute = SlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const BuscaRoute = BuscaRouteImport.update({
  id: '/busca',
  path: '/busca',
  getParentRoute: () => rootRouteImport,
} as any)
const ChacarasRoute = ChacarasRouteImport.update({
  id: '/chacaras',
  path: '/chacaras',
  getParentRoute: () => rootRouteImport,
} as any)
const ChalesRoute = ChalesRouteImport.update({
  id: '/chales',
  path: '/chales',
  getParentRoute: () => rootRouteImport,
} as any)
const PesqueirosRoute = PesqueirosRouteImport.update({
  id: '/pesqueiros',
  path: '/pesqueiros',
  getParentRoute: () => rootRouteImport,
} as any)
const RefugiosUrbanosRoute = RefugiosUrbanosRouteImport.update({
  id: '/refugios-urbanos',
  path: '/refugios-urbanos',
  getParentRoute: () => rootRouteImport,
} as any)
const SitiosRoute = SitiosRouteImport.update({
  id: '/sitios',
  path: '/sitios',
  getParentRoute: () => rootRouteImport,
} as any)
const TemporadaRoute = TemporadaRouteImport.update({
  id: '/temporada',
  path: '/temporada',
  getParentRoute: () => rootRouteImport,
} as any)
const TiposDeImoveisRuraisRoute = TiposDeImoveisRuraisRouteImport.update({
  id: '/tipos-de-imoveis-rurais',
  path: '/tipos-de-imoveis-rurais',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const ImovelSlugRoute = ImovelSlugRouteImport.update({
  id: '/imovel/$slug',
  path: '/imovel/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const TipoDePropriedadeSlugRoute = TipoDePropriedadeSlugRouteImport.update({
  id: '/tipo-de-propriedade/$slug',
  path: '/tipo-de-propriedade/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/blog': typeof BlogRouteWithChildren
  '/busca': typeof BuscaRoute
  '/chacaras': typeof ChacarasRoute
  '/chales': typeof ChalesRoute
  '/pesqueiros': typeof PesqueirosRoute
  '/refugios-urbanos': typeof RefugiosUrbanosRoute
  '/sitios': typeof SitiosRoute
  '/temporada': typeof TemporadaRoute
  '/tipos-de-imoveis-rurais': typeof TiposDeImoveisRuraisRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/imovel/$slug': typeof ImovelSlugRoute
  '/tipo-de-propriedade/$slug': typeof TipoDePropriedadeSlugRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/busca': typeof BuscaRoute
  '/chacaras': typeof ChacarasRoute
  '/chales': typeof ChalesRoute
  '/pesqueiros': typeof PesqueirosRoute
  '/refugios-urbanos': typeof RefugiosUrbanosRoute
  '/sitios': typeof SitiosRoute
  '/temporada': typeof TemporadaRoute
  '/tipos-de-imoveis-rurais': typeof TiposDeImoveisRuraisRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/imovel/$slug': typeof ImovelSlugRoute
  '/tipo-de-propriedade/$slug': typeof TipoDePropriedadeSlugRoute
  '/blog': typeof BlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/blog': typeof BlogRouteWithChildren
  '/busca': typeof BuscaRoute
  '/chacaras': typeof ChacarasRoute
  '/chales': typeof ChalesRoute
  '/pesqueiros': typeof PesqueirosRoute
  '/refugios-urbanos': typeof RefugiosUrbanosRoute
  '/sitios': typeof SitiosRoute
  '/temporada': typeof TemporadaRoute
  '/tipos-de-imoveis-rurais': typeof TiposDeImoveisRuraisRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/imovel/$slug': typeof ImovelSlugRoute
  '/tipo-de-propriedade/$slug': typeof TipoDePropriedadeSlugRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$slug'
    | '/blog'
    | '/busca'
    | '/chacaras'
    | '/chales'
    | '/pesqueiros'
    | '/refugios-urbanos'
    | '/sitios'
    | '/temporada'
    | '/tipos-de-imoveis-rurais'
    | '/blog/$slug'
    | '/imovel/$slug'
    | '/tipo-de-propriedade/$slug'
    | '/blog/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$slug'
    | '/busca'
    | '/chacaras'
    | '/chales'
    | '/pesqueiros'
    | '/refugios-urbanos'
    | '/sitios'
    | '/temporada'
    | '/tipos-de-imoveis-rurais'
    | '/blog/$slug'
    | '/imovel/$slug'
    | '/tipo-de-propriedade/$slug'
    | '/blog'
  id:
    | '__root__'
    | '/'
    | '/$slug'
    | '/blog'
    | '/busca'
    | '/chacaras'
    | '/chales'
    | '/pesqueiros'
    | '/refugios-urbanos'
    | '/sitios'
    | '/temporada'
    | '/tipos-de-imoveis-rurais'
    | '/blog/$slug'
    | '/imovel/$slug'
    | '/tipo-de-propriedade/$slug'
    | '/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SlugRoute: typeof SlugRoute
  BlogRoute: typeof BlogRouteWithChildren
  BuscaRoute: typeof BuscaRoute
  ChacarasRoute: typeof ChacarasRoute
  ChalesRoute: typeof ChalesRoute
  PesqueirosRoute: typeof PesqueirosRoute
  RefugiosUrbanosRoute: typeof RefugiosUrbanosRoute
  SitiosRoute: typeof SitiosRoute
  TemporadaRoute: typeof TemporadaRoute
  TiposDeImoveisRuraisRoute: typeof TiposDeImoveisRuraisRoute
  ImovelSlugRoute: typeof ImovelSlugRoute
  TipoDePropriedadeSlugRoute: typeof TipoDePropriedadeSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug': {
      id: '/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof SlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/busca': {
      id: '/busca'
      path: '/busca'
      fullPath: '/busca'
      preLoaderRoute: typeof BuscaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chacaras': {
      id: '/chacaras'
      path: '/chacaras'
      fullPath: '/chacaras'
      preLoaderRoute: typeof ChacarasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chales': {
      id: '/chales'
      path: '/chales'
      fullPath: '/chales'
      preLoaderRoute: typeof ChalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pesqueiros': {
      id: '/pesqueiros'
      path: '/pesqueiros'
      fullPath: '/pesqueiros'
      preLoaderRoute: typeof PesqueirosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refugios-urbanos': {
      id: '/refugios-urbanos'
      path: '/refugios-urbanos'
      fullPath: '/refugios-urbanos'
      preLoaderRoute: typeof RefugiosUrbanosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitios': {
      id: '/sitios'
      path: '/sitios'
      fullPath: '/sitios'
      preLoaderRoute: typeof SitiosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/temporada': {
      id: '/temporada'
      path: '/temporada'
      fullPath: '/temporada'
      preLoaderRoute: typeof TemporadaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tipos-de-imoveis-rurais': {
      id: '/tipos-de-imoveis-rurais'
      path: '/tipos-de-imoveis-rurais'
      fullPath: '/tipos-de-imoveis-rurais'
      preLoaderRoute: typeof TiposDeImoveisRuraisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/imovel/$slug': {
      id: '/imovel/$slug'
      path: '/imovel/$slug'
      fullPath: '/imovel/$slug'
      preLoaderRoute: typeof ImovelSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tipo-de-propriedade/$slug': {
      id: '/tipo-de-propriedade/$slug'
      path: '/tipo-de-propriedade/$slug'
      fullPath: '/tipo-de-propriedade/$slug'
      preLoaderRoute: typeof TipoDePropriedadeSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SlugRoute: SlugRoute,
  BlogRoute: BlogRouteWithChildren,
  BuscaRoute: BuscaRoute,
  ChacarasRoute: ChacarasRoute,
  ChalesRoute: ChalesRoute,
  PesqueirosRoute: PesqueirosRoute,
  RefugiosUrbanosRoute: RefugiosUrbanosRoute,
  SitiosRoute: SitiosRoute,
  TemporadaRoute: TemporadaRoute,
  TiposDeImoveisRuraisRoute: TiposDeImoveisRuraisRoute,
  ImovelSlugRoute: ImovelSlugRoute,
  TipoDePropriedadeSlugRoute: TipoDePropriedadeSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
